### ISSUE TITLE
Waypoints not working if using a forge server and multiplayer

### ISSUE THREAD

**Issue by starfishmod** [kamildanak/Waypoints#1]
I have a local forge server (non-gui) set up and I players sign in. I can create way points and travel between them. However when other players try to use the way points they don't work or list the way points. If they create way points I then can't use their way points either.
Can it be set-up so the way points available are stored on the server for all players?
Thanks for the awesome mod btw :)

**Comment by kamildanak** [comment]
Fixed by adding CommonDiscoveryList option in commit 849ccd24ed53b86952c119e0e7a1d2b1dce667dc.
