### ISSUE TITLE
[1.10.2] Waypoints "forgetting" their lists

### ISSUE THREAD

**Issue by kwpugh** [kamildanak/Waypoints#2]
Forge: 2014
Mod: waypoints-1.9.4-1.2.1.jar

After players logout/log back in, the waypoints they created seem to "forget" their list of locations.

**Comment by kamildanak** [comment]
Waypoints do not remember locations, players do - every player has a list of discovered waypoints that he can teleport to.
One, shared list will be available as an option soon.

**Comment by kwpugh** [comment]
ok, the player's lists are losing their waypoints, to be more correct.

**Comment by kamildanak** [comment]
Oh, ok now I've got it.
Unfortunately I was unable to replicate the bug myself.
I will add an optional logger to the new version, so i can see what went wrong.

**Comment by durand1w** [comment]
I'm seeing this issue as well on the 1.10 release.  Is there anything I can provide or check to help identify a cause?
