### ISSUE TITLE
Add this Issue tracker to the CurseForge page

### ISSUE THREAD

**Issue by C0rn3j** [kamildanak/Waypoints#3]
[Waypoints](https://minecraft.curseforge.com/projects/waypoints) should have an "Issues" button linking here like [this mod has](https://minecraft.curseforge.com/projects/deep-resonance) for example

**Comment by kamildanak** [comment]
Fixed, thank you for noticing.

**Comment by C0rn3j** [comment]
Thanks for fixing it so quick! By the way, when you resolve an issue on Github, the issue should then be closed ^^
